# Generated by Django 4.2.9 on 2024-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.IntegerField(unique=True),
        ),
    ]
